In [2]:
import numpy as np

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\ml\modular\ml-class\Data\Advertising.csv')
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [11]:
x=df.drop(['Sales','Unnamed: 0'],axis=1)
x.head()


TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [16]:
y=df['Sales']
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: Sales, dtype: float64

In [19]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_conv=PolynomialFeatures(degree=3,include_bias=False)


In [20]:
final_model1=LinearRegression()

In [22]:
poly_features=poly_conv.fit_transform(x)
poly_features

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [23]:
x.shape

(200, 3)

In [24]:
poly_features.shape

(200, 19)

In [31]:
from sklearn.model_selection import train_test_split

In [43]:
from sklearn.model_selection import train_test_split

In [46]:
help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
    Split arrays or matrices into random train and test subsets.
    
    Quick utility that wraps input validation and
    ``next(ShuffleSplit().split(X, y))`` and application to input data
    into a single call for splitting (and optionally subsampling) data in a
    oneliner.
    
    Read more in the :ref:`User Guide <cross_validation>`.
    
    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.
    
    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to 

In [57]:
x_train,x_test,y_train,y_test=train_test_split(poly_features,y, test_size=0.33, train_size=None, random_state=101)

In [58]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()


In [59]:
scaler.fit(x_tarin)

StandardScaler()

In [60]:
scaled_x_train=scaler.transform(x_train)

In [61]:
scaled_x_train=scaler.transform(x_test)

In [62]:
x_train[0]

array([1.87800000e+02, 2.11000000e+01, 9.50000000e+00, 3.52688400e+04,
       3.96258000e+03, 1.78410000e+03, 4.45210000e+02, 2.00450000e+02,
       9.02500000e+01, 6.62348815e+06, 7.44172524e+05, 3.35053980e+05,
       8.36104380e+04, 3.76445100e+04, 1.69489500e+04, 9.39393100e+03,
       4.22949500e+03, 1.90427500e+03, 8.57375000e+02])

In [63]:
scaled_x_train[0]

array([-0.88585021,  1.78850357,  0.75279488, -0.94268603,  0.04504514,
       -0.24391745,  2.35286478,  1.66213511,  0.43363357, -0.85817564,
       -0.5194069 , -0.51483477,  0.48397764,  0.26923803, -0.14681754,
        2.81970897,  2.22798415,  0.9755699 ,  0.14551054])

In [66]:
from sklearn.linear_model import Ridge

In [68]:
ridge_model=Ridge(alpha=10)

In [70]:
ridge_model.fit(x_train,y_train)

Ridge(alpha=10)

In [72]:
test_predictions=ridge_model.predict(x_test)

In [73]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [74]:
MAE=mean_absolute_error(y_test,test_predictions)

In [75]:
MAE

0.3930126552894761

In [76]:
RMSE=np.sqrt(mean_squared_error(y_test, test_predictions))

In [77]:
RMSE

0.5579455029352857